In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("/Users/ishaangupta/Downloads/GIT HUB FILES/Social_Network_Ads.csv")
df=df.iloc[:,2:]
df.sample(5)

     Age  EstimatedSalary  Purchased
62    23            66000          0
336   58           144000          1
140   19            85000          0
114   42            80000          0
173   34            43000          0

***TRAIN TEST SPLIT***

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop("Purchased",axis=1),df["Purchased"],test_size=.3,random_state=0)
X_train.shape

(280, 2)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_test_Scaled=scaler.transform(X_train)
X_train_Scaled=scaler.transform(X_train)
X_test_Scaled=pd.DataFrame(X_test_Scaled,columns=X_test.columns)
X_train_Scaled=pd.DataFrame(X_train_Scaled,columns=X_train.columns)
X_train_Scaled

          Age  EstimatedSalary
0   -1.163172        -1.584970
1    2.170181         0.930987
2    0.013305         1.220177
3    0.209385         1.075582
4    0.405465        -0.486047
..        ...              ...
275  0.993704        -1.151185
276 -0.869053        -0.775237
277 -0.182774        -0.514966
278 -1.065133        -0.457127
279 -1.163172         1.393691

[280 rows x 2 columns]

In [ ]:
np.round(X_train_Scaled.describe())